/** Shape of site/public/catalog.json (generated by @linglongjs/marketplace). */

export type Skill = {
  id: string;
  folder: string;
  path: string;
  description: string;
  folderUrl: string;
  copyCommand: string;
  search: string;
};

export type PluginRow = {
  name: string;
  description: string;
  skillCount: number;
};

export type SiteCatalog = {
  marketTitle: string;
  metaDescription: string;
  version: string | null;
  generatedAt: string;
  repository: string;
  sourceBranch: string;
  cloneUrl: string;
  repoName: string;
  marketplaceName: string;
  pagesUrl: string;
  pagesCatalogUrl: string;
  pagesManifestUrl: string;
  marketplaceManifestRawUrl: string;
  repositoryUrl: string;
  installScriptRawUrl: string;
  installScriptPagesUrl: string;
  plugins: PluginRow[];
  skills: Skill[];
};
