import { useEffect, useState } from "react";
import type { SiteCatalog } from "../types/catalog";

type State =
  | { status: "loading" }
  | { status: "ok"; data: SiteCatalog }
  | { status: "error"; message: string };

/**
 * Loads catalog.json from the same origin (Vite base-aware).
 * catalog.json is generated by `ll-catalog` / @linglongjs/marketplace-build (site prebuild).
 */
export function useSiteCatalog(): State {
  const [state, setState] = useState<State>({ status: "loading" });

  useEffect(() => {
    const catalogUrl = `${import.meta.env.BASE_URL}catalog.json`;
    fetch(catalogUrl)
      .then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        return res.json() as Promise<SiteCatalog>;
      })
      .then((data) => {
        if (!data || typeof data !== "object" || !Array.isArray(data.skills)) {
          throw new Error("Invalid catalog.json shape");
        }
        setState({ status: "ok", data });
      })
      .catch((e: unknown) => {
        const message = e instanceof Error ? e.message : "Failed to load catalog";
        setState({ status: "error", message });
      });
  }, []);

  return state;
}
